"""added breed column

Revision ID: 90c12dea460f
Revises: 
Create Date: 2023-11-08 15:41:31.496552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c12dea460f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
